import type { NextPage } from 'next';
import Head from 'next/head';
import Logo from '../components/Logo';
import TipCalculatorCard from '../components/TipCalculatorCard';

const Home: NextPage = () => {
  return (
    <div className="md:flex md:items-center md:justify-center md:flex-col md:gap-4 md:min-h-screen">
      <Head>
        <title>Tip Calculator App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="mx-auto my-10 md:my-16">
        <Logo />
      </header>

      <main>
        <section className="max-w-[57.5rem] w-full">
          <TipCalculatorCard />
        </section>
      </main>
    </div>
  );
};

export default Home;
